[BC-010] Demo fixes
sspr/brothers-challange pull request #11
Opened 2022-02-25 13:54 UTC by sspr

2022-02-28 17:31 UTC, szumike commented on src/app/App.tsx
> +    () => <Snackbar text={!isAuthenticated && prevIsAuth ? formatMessage({ id: 'logout.message' }) : undefined} />,
`prevIsAuth` jest zawsze przeciwieństwem `isAuthenticated`, prawda? W końcu to jest boolean. Więc pytanie czy tutaj trzeba tego używać

2022-02-28 17:31 UTC, szumike commented on src/app/App.tsx
> +  const snackbar = useMemo(
Jaki jest cel użycia tutaj `useMemo`?

2022-03-01 11:31 UTC, szumike requested changes

2022-03-01 11:31 UTC, szumike commented on src/ui/snackbar/Snackbar.tsx
> +  }, [text]);
Tu jest jeden problem - a co jeśli po sobie będziesz chciał wyświetlić dwa razy ten sam tekst? ;)
Myślę że `isOpen` i `onClose` można wyciągnąć jako propsy, `isOpen = !!text` w kontekście, a `handleClose = () => setText(null)`

2022-03-01 12:05 UTC, sspr commented on src/ui/snackbar/Snackbar.tsx
> +  }, [text]);
Zrobiłem tak, ale `isOpen` jako props jest niepotrzebny - możemy sobie zrobić `!!text` już w `Snackbarze`

2022-03-01 12:25 UTC, szumike approved these changes

2022-03-01 12:33 UTC, merged